apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinysafety-streamlit
spec:
  replicas: 1 # Starts with 1 pod
  selector:
    matchLabels:
      app: streamlit-dashboard
  template:
    metadata:
      labels:
        app: streamlit-dashboard
    spec:
      containers:
      - name: streamlit
        image: tinysafety-streamlit:v1
        imagePullPolicy: Never # CRITICAL: Tells K8s to use your local image, not the internet
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer 
  selector:
    app: streamlit-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501