name: TinySafetyNet-MLOps
on: [push]

jobs:
  audit-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: pip install pandas mlflow great_expectations

      - name: Run Integrity Validation
        run: python week5/validate_data.py

      - name: Run Drift Detection
        run: python week5/drift_detector.py